---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: team-2
spec:
  limits:
  - max:
      cpu: 300m
      memory: 1Gi
    type: Container
  - max:
      storage: 2Gi
    type: PersistentVolumeClaim
